{
  imports = [
    ./disks
    ./boot.nix
    ./env.nix
    ./opengl.nix
    ./networking.nix
    ./services.nix
    ./sound.nix
    ./users.nix
    ./packages.nix
    ./nix.nix
    ./system.nix
    ./fonts.nix
    ./virtualisation.nix
    ./shell.nix
    ./steam.nix
    ./hardware.nix
  ];
}
